version: '3' # composeファイルのバーション指定
services:
  # service名
  app:
    build: ./docker/golang
    tty: true # コンテナの起動永続化
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
    command: go run main.go