name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./hello

    - name: Test
      run: go test -v ./api/*

    - name: Notify Slack
      run: |
        data=$(cat <<EOF
        {
          "channel": "C01412D7U30",
          "username": "ga",
          "text": "SuccessしたGithubActinosのWorkflowがあります"
        }
        EOF
        )
        curl -X POST \
             -H "Content-type: application/json; charset=utf-8" \
             -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
             -d "$data" \
             https://slack.com/api/chat.postMessage
